/**
 * Pill-Based Narrative Timeline Types
 *
 * This module defines the core types for the pill-based narrative system.
 *
 * Structure:
 * - Task Decomposer generates Tasks
 * - Each Task has a title and contains Tool Pills
 * - Each Tool Pill represents a tool execution (web_search, browser_use, etc.)
 * - Clicking a pill opens the Tool Detail Side Panel
 */

/**
 * Execution status for tasks and tool pills
 */
export type ExecutionStatus = 'pending' | 'in-progress' | 'completed' | 'failed' | 'skipped';

/**
 * A tool pill representing a single tool execution within a task
 */
export interface ToolPill {
  /** Unique identifier for this pill */
  id: string;

  /** Name of the tool (e.g., "web_search", "browser_use", "read_file") */
  toolName: string;

  /** Status of this tool execution */
  status: ExecutionStatus;

  /** Icon to display in the pill (emoji or icon name) */
  icon?: string;

  /** Label for the pill (e.g., "Search", "Browse", "Read") */
  label?: string;

  /** Parameters passed to the tool */
  parameters?: Record<string, any>;

  /** Result or output from the tool */
  result?: string;

  /** Error message if tool failed */
  error?: string;

  /** Timestamp when tool started */
  startTime?: number;

  /** Timestamp when tool completed */
  endTime?: number;

  /** IDs of pills this pill depends on */
  dependsOn?: string[];

  /** Metadata for rendering and styling */
  metadata?: {
    /** Custom color for the pill */
    color?: string;
    /** Custom styling class */
    className?: string;
  };
}

/**
 * A task generated by the task decomposer
 */
export interface Task {
  /** Unique identifier for this task */
  id: string;

  /** Task title/name (e.g., "Search for Discord bots") */
  title: string;

  /** Description of what this task accomplishes */
  description?: string;

  /** Tool pills executed for this task, in chronological order */
  pills: ToolPill[];

  /** Overall status of the task */
  status: ExecutionStatus;

  /** Timestamp when task started */
  startTime?: number;

  /** Timestamp when task completed */
  endTime?: number;

  /** Whether this task is collapsed in the UI */
  isCollapsed?: boolean;
}

/**
 * Complete narrative timeline
 */
export interface NarrativeTimeline {
  /** Unique identifier for this timeline */
  missionId: string;

  /** Ordered list of tasks */
  tasks: Task[];

  /** Overall status of the entire timeline */
  status: ExecutionStatus;

  /** Timestamp when timeline started */
  startTime: number;

  /** Timestamp when timeline completed */
  endTime?: number;

  /** Metadata about the timeline */
  metadata?: {
    /** User's original request */
    userRequest?: string;
    /** Agent that generated this timeline */
    agent?: string;
    /** Model used */
    model?: string;
  };
}

/**
 * Validation error for narrative structures
 */
export interface ValidationError {
  /** Type of validation error */
  type: 'invalid_reference' | 'circular_dependency' | 'missing_field' | 'invalid_status';

  /** Human-readable error message */
  message: string;

  /** ID of the element that caused the error */
  elementId?: string;
}

/**
 * Validation result
 */
export interface ValidationResult {
  /** Whether the structure is valid */
  isValid: boolean;

  /** List of validation errors (empty if valid) */
  errors: ValidationError[];
}
