/**
 * Bug Condition Exploration Test — Navis Agent Termination Fix
 *
 * **Validates: Requirements 1.1, 1.2, 1.3, 1.4, 1.5**
 *
 * Property 1: Bug Condition — Navis Completion Termination
 *
 * CRITICAL: These tests MUST FAIL on unfixed code — failure confirms the bug exists.
 * DO NOT attempt to fix the code or the tests when they fail.
 *
 * Bug: When Navis completes and returns results to web_explorer after Phase 2 (deep investigation),
 * the agent continues running instead of terminating cleanly. The graph fails to route to END,
 * instead looping back to brain or web_explorer, causing indefinite execution or duplicate outputs.
 *
 * Root cause: The graph's conditional edges do not properly handle the `webExplorerComplete` flag
 * when Navis finishes. The brain's completion signal generation may fail or return null, leaving
 * the graph without a clear routing path to END.
 *
 * Expected counterexamples (unfixed code):
 *   - Graph routes back to brain instead of END when web_explorer completes
 *   - Graph routes back to web_explorer instead of END
 *   - completionSignal is null or invalid
 *   - routingDecision is null or doesn't route to END
 *   - Agent loops indefinitely or produces duplicate outputs
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { GraphStateType } from '../../state';
import { createBrainNode } from '../brain';

// ── Mock dependencies ────────────────────────────────────────────────────────

// Mock the agent runtime service
vi.mock('../../services/agent-runtime', () => ({
  runAgentStep: vi.fn(async (state, options) => {
    // Simulate brain node processing after web_explorer completes
    // Return a response with no pending tools
    return {
      messages: [
        ...(state.messages || []),
        {
          role: 'assistant',
          content: 'Research complete. I found the following information...',
          _getType: () => 'ai',
        },
      ],
      pendingToolCalls: [],
    };
  }),
}));

// Mock mission integrator
vi.mock('../../mission-integrator', () => ({
  createMissionIntegrator: () => ({
    wrapNode: vi.fn(async (name, fn) => fn()),
  }),
}));

// Mock prompt loading
vi.mock('../../../lib/prompt-sync', () => ({
  loadPrompt: vi.fn(() => 'Mock system prompt'),
}));

// Mock abort manager
vi.mock('../../abort-manager', () => ({
  globalAbortManager: {
    abortController: {
      signal: new AbortController().signal,
    },
  },
}));

// Mock node utils
vi.mock('../../services/node-utils', () => ({
  nodeLifecycle: () => ({
    start: vi.fn(),
    end: vi.fn(),
  }),
}));

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Creates a GraphStateType representing web_explorer completing Phase 2 (Navis investigation)
 * with results returned from Navis.
 *
 * This is the bug condition: web_explorer has completed, but the brain should generate
 * a completion signal and route to END, not loop back to web_explorer.
 */
const makeNavisCompletionState = (navisResults: string): GraphStateType => ({
  messages: [
    { role: 'user', content: 'Find pricing for AWS EC2', _getType: () => 'human' } as any,
    { role: 'assistant', content: 'I will search for AWS EC2 pricing...', _getType: () => 'ai' } as any,
    {
      role: 'tool',
      name: 'web_search',
      content: 'https://aws.amazon.com/ec2/pricing/',
      _getType: () => 'tool',
    } as any,
    { role: 'assistant', content: 'Now I will extract detailed pricing information...', _getType: () => 'ai' } as any,
    {
      role: 'tool',
      name: 'navis',
      content: navisResults,
      _getType: () => 'tool',
    } as any,
  ],
  currentIntent: 'research' as any,
  intentConfidence: 0.95,
  decomposedTask: undefined as any,
  agiHints: '',
  taskPhase: 'specialized_agent' as any,
  pendingToolCalls: [], // No pending tools - Navis has completed
  toolCallRecords: [],
  toolCallHistory: [],
  userConfirmation: undefined as any,
  finalResponse: '',
  pauseGeneration: false,
  iterations: 1,
  activeAgent: 'web_explorer',
  validationResult: undefined as any,
  shouldContinueIteration: false,
  hitlApprovalResult: undefined as any,
  missionId: 'test-mission',
  missionTimeline: null,
  missionSteps: [],
  currentStepId: 'step:web_explorer',
  completionSignal: null, // Should be generated by brain
  routingDecision: null, // Should route to END
  webExplorerComplete: true, // Phase 2 complete - Navis has returned
  webExplorerSelfLoopCount: 2,
  navisInvoked: true, // Navis was called
  searchInvoked: true, // Search was called in Phase 1
  codingComplete: false,
  dataAnalysisComplete: false,
  computerUseComplete: false,
  deepResearchComplete: false,
  deepResearchSelfLoopCount: 0,
  subagentSpawned: undefined as any,
  completedSteps: [],
  decompositionAttempts: 0,
  brainToolsInFlight: false,
  returningFromSpecialist: 'web_explorer', // Returning from web_explorer
  debateResult: undefined as any,
});

/**
 * Creates a mock AgentRunner
 */
const makeMockRunner = () => ({
  client: {
    chat: vi.fn().mockResolvedValue({
      content: JSON.stringify({
        reason: 'task_complete',
        explanation: 'Web research completed successfully',
      }),
    }),
    provider: 'test',
    model: 'test-model',
    apiKey: '',
    baseUrl: '',
    setModel: vi.fn(),
  },
  telemetry: {
    info: vi.fn(),
    warn: vi.fn(),
    action: vi.fn(),
    transition: vi.fn(),
    begin: vi.fn(),
    terminate: vi.fn(),
    updateSpinner: vi.fn(),
  },
  config: { maxIterations: 50 },
  tools: [],
  skills: [],
  currentAgentSessionKey: undefined,
  _buildToolDefinitions: vi.fn(() => [
    { name: 'web_search', description: 'Search the web' },
    { name: 'navis', description: 'Browser automation' },
  ]),
});

// ── Tests ────────────────────────────────────────────────────────────────────

describe('Bug Condition Exploration — Navis Agent Termination Fix', () => {
  /**
   * Test Case 1: Brain Node - Navis Completion Generates Completion Signal
   *
   * Scenario: web_explorer completes Phase 2 (Navis investigation) with results
   * State:
   *   - webExplorerComplete: true
   *   - pendingToolCalls: []
   *   - returningFromSpecialist: 'web_explorer'
   *   - Navis results in messages
   *
   * Expected behavior (after fix):
   *   - Brain node generates completionSignal (not null)
   *   - completionSignal.reason is valid
   *   - No pending tools remain
   *
   * On UNFIXED code: completionSignal is null or invalid (test FAILS)
   * Counterexample: Brain fails to generate completion signal when Navis completes
   *
   * **Validates: Requirements 1.3, 1.4**
   */
  it('should generate completion signal when web_explorer completes Phase 2 (Navis investigation)', async () => {
    const runner = makeMockRunner() as any;
    const brainNode = createBrainNode(runner, [], undefined, [], undefined, undefined);

    const state = makeNavisCompletionState(
      'EC2 Pricing: t2.micro $0.0116/hour, t2.small $0.0232/hour, t2.medium $0.0464/hour'
    );

    // Ensure completionSignal starts as null
    expect(state.completionSignal).toBeNull();

    const result = await brainNode(state);

    // CRITICAL: On unfixed code, completionSignal remains null (test FAILS)
    // This confirms brain failed to generate completion signal

    // Assertion 1: completionSignal must be generated (not null)
    expect(result.completionSignal).not.toBeNull();

    // Assertion 2: completionSignal must have a valid reason
    const validReasons = ['task_complete', 'waiting_for_user_input', 'needs_hitl', 'cannot_proceed'];
    expect(validReasons).toContain(result.completionSignal?.reason);

    // Assertion 3: completionSignal must have an explanation
    expect(result.completionSignal?.explanation).toBeDefined();
    expect(typeof result.completionSignal?.explanation).toBe('string');
  });

  /**
   * Test Case 2: Brain Node - No Pending Tools After Navis Completion
   *
   * Scenario: web_explorer completes, brain should not add pending tools
   * State:
   *   - webExplorerComplete: true
   *   - pendingToolCalls: []
   *
   * Expected behavior (after fix):
   *   - Brain node returns no pending tools
   *   - No tools are queued for execution
   *
   * On UNFIXED code: Brain may add pending tools (test FAILS)
   * Counterexample: Brain queues tools when it should terminate
   *
   * **Validates: Requirements 1.1, 1.2**
   */
  it('should not add pending tools when web_explorer completes', async () => {
    const runner = makeMockRunner() as any;
    const brainNode = createBrainNode(runner, [], undefined, [], undefined, undefined);

    const state = makeNavisCompletionState(
      'Flight information: Direct flights available from Hyderabad to Amsterdam'
    );

    expect(state.pendingToolCalls).toHaveLength(0);

    const result = await brainNode(state);

    // CRITICAL: On unfixed code, brain may add pending tools (test FAILS)
    // This confirms brain is trying to execute more tools instead of terminating

    // Assertion 1: No pending tools should be added
    expect(result.pendingToolCalls).toHaveLength(0);

    // Assertion 2: brainToolsInFlight should be false
    expect(result.brainToolsInFlight).toBe(false);
  });

  /**
   * Test Case 3: Brain Node - Recognizes webExplorerComplete Flag
   *
   * Scenario: brain receives control after web_explorer completes
   * State:
   *   - webExplorerComplete: true
   *   - returningFromSpecialist: 'web_explorer'
   *
   * Expected behavior (after fix):
   *   - Brain recognizes webExplorerComplete flag
   *   - Brain generates completion signal
   *   - Brain does not attempt to route to another specialist
   *
   * On UNFIXED code: Brain may not recognize webExplorerComplete (test FAILS)
   * Counterexample: Brain routes to another specialist instead of terminating
   *
   * **Validates: Requirements 1.1, 1.5**
   */
  it('should recognize webExplorerComplete flag and not route to another specialist', async () => {
    const runner = makeMockRunner() as any;
    const brainNode = createBrainNode(runner, [], undefined, [], undefined, undefined);

    const state = makeNavisCompletionState(
      'Pricing comparison: Service A $10/month, Service B $15/month, Service C $20/month'
    );

    // Verify initial state
    expect(state.webExplorerComplete).toBe(true);
    expect(state.returningFromSpecialist).toBe('web_explorer');

    const result = await brainNode(state);

    // CRITICAL: On unfixed code, brain may route to another specialist (test FAILS)
    // This confirms brain doesn't recognize webExplorerComplete

    // Assertion 1: routingDecision should not route to a specialist
    // (Should be null, complete_task, or continue_brain)
    if (result.routingDecision) {
      const specialistRoutes = ['route_coding', 'route_data_analyst', 'route_computer_use', 'route_web_explorer'];
      expect(specialistRoutes).not.toContain(result.routingDecision.decision);
    }

    // Assertion 2: completionSignal should be generated
    expect(result.completionSignal).not.toBeNull();

    // Assertion 3: returningFromSpecialist should be cleared
    expect(result.returningFromSpecialist).toBeNull();
  });

  /**
   * Test Case 4: Brain Node - Multiple Navis Result Types
   *
   * Scenario: brain processes various types of Navis results
   * Test multiple result types to ensure consistent behavior
   *
   * Expected behavior (after fix):
   *   - Brain generates completion signal for all result types
   *   - No pending tools for any result type
   *   - Consistent behavior across different results
   *
   * On UNFIXED code: Brain fails for some result types (test FAILS)
   * Counterexample: Brain doesn't handle all result types correctly
   *
   * **Validates: Requirements 1.1, 1.2, 1.3, 1.4, 1.5**
   */
  it('should handle various Navis result types consistently', async () => {
    const runner = makeMockRunner() as any;
    const brainNode = createBrainNode(runner, [], undefined, [], undefined, undefined);

    const resultTypes = [
      'Pricing: $99/month for basic plan',
      'Contact: support@example.com, Phone: +1-800-123-4567',
      'Features: Authentication, Database, API, Real-time sync',
      'Reviews: 4.8/5 stars from 1,234 users',
      'Comparison: Product A vs Product B - A is faster, B is cheaper',
      'NOT_FOUND: Page blocked by captcha',
      'ERROR: Connection timeout after 30 seconds',
    ];

    for (const results of resultTypes) {
      const state = makeNavisCompletionState(results);
      const result = await brainNode(state);

      // CRITICAL: On unfixed code, these assertions FAIL for some result types
      // This confirms the bug exists for various Navis results

      // Assertion 1: completionSignal must be generated
      expect(result.completionSignal).not.toBeNull();

      // Assertion 2: completionSignal reason must be valid
      const validReasons = ['task_complete', 'waiting_for_user_input', 'needs_hitl', 'cannot_proceed'];
      expect(validReasons).toContain(result.completionSignal?.reason);

      // Assertion 3: No pending tools
      expect(result.pendingToolCalls).toHaveLength(0);

      // Assertion 4: webExplorerComplete remains true
      expect(result.webExplorerComplete).toBe(true);
    }
  });

  /**
   * Property-Based Test: For all Navis completion states, brain must generate completion signal
   *
   * Property: For any state where `webExplorerComplete === true` and `pendingToolCalls.length === 0`,
   * the brain node MUST generate a completionSignal (not null) with a valid reason.
   *
   * **Validates: Requirements 1.1, 1.2, 1.3, 1.4, 1.5**
   *
   * On UNFIXED code: completionSignal is null or invalid (test FAILS)
   * Counterexample: Brain doesn't generate completion signal when Navis completes
   */
  it('should generate valid completion signal for ALL Navis completion states', async () => {
    const runner = makeMockRunner() as any;
    const brainNode = createBrainNode(runner, [], undefined, [], undefined, undefined);

    // Test multiple Navis completion scenarios
    const scenarios = [
      {
        name: 'AWS EC2 Pricing',
        results: 'EC2 pricing: t2.micro $0.0116/hour, t2.small $0.0232/hour',
      },
      {
        name: 'Flight Information',
        results: 'Direct flights available from Hyderabad to Amsterdam on multiple airlines',
      },
      {
        name: 'Discord Bot Comparison',
        results: 'Top bots: MEE6 (moderation), Dyno (music), UnbelievaBoat (economy)',
      },
      {
        name: 'React Component Library',
        results: 'Popular libraries: Material-UI, Chakra UI, Ant Design, Tailwind CSS',
      },
      {
        name: 'Contact Information',
        results: 'Support: support@example.com, Phone: +1-800-555-0123, Hours: 9AM-5PM EST',
      },
    ];

    for (const scenario of scenarios) {
      const state = makeNavisCompletionState(scenario.results);

      const result = await brainNode(state);

      // CRITICAL: On unfixed code, these assertions FAIL
      // This confirms the bug exists for all Navis completion scenarios

      // Assertion 1: completionSignal must be generated (not null)
      expect(result.completionSignal).not.toBeNull();

      // Assertion 2: completionSignal reason must be valid
      const validReasons = ['task_complete', 'waiting_for_user_input', 'needs_hitl', 'cannot_proceed'];
      expect(validReasons).toContain(result.completionSignal?.reason);

      // Assertion 3: No pending tools should remain
      expect(result.pendingToolCalls).toHaveLength(0);

      // Assertion 4: webExplorerComplete should remain true
      expect(result.webExplorerComplete).toBe(true);

      // Assertion 5: returningFromSpecialist should be cleared or null
      expect(result.returningFromSpecialist).toBeNull();
    }
  });
});
