/**
 * Property-Based Test: Step Counter Sequential Increment
 *
 * **Validates: Requirements 1.5**
 *
 * Property 1: Step Counter Sequential Increment
 *
 * For any sequence of sub-agent steps, the step numbers SHALL increment
 * sequentially starting from 1 (i.e., 1, 2, 3, ..., N) with no gaps or duplicates.
 *
 * Feature: sub-agent-progress-streaming, Property 1: Step Counter Sequential Increment
 */

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';

type SubAgentProgressEvent = {
  type: 'step' | 'reasoning' | 'action' | 'screenshot' | 'complete' | 'abort';
  toolCallId: string;
  timestamp: string;
  stepNumber?: number;
  totalSteps?: number;
  content?: string;
  action?: {
    type: string;
    params: Record<string, unknown>;
    description: string;
  };
  screenshot?: {
    base64: string;
    width: number;
    height: number;
  };
  metadata?: Record<string, unknown>;
};

describe('Feature: sub-agent-progress-streaming, Property 1: Step Counter Sequential Increment', () => {
  /**
   * Property Test: Step numbers form sequential sequence [1, 2, 3, ..., N]
   *
   * This test verifies that for any sequence of step events generated by a sub-agent,
   * the stepNumber values form a sequential sequence starting from 1 with no gaps.
   *
   * Test Strategy:
   * 1. Generate random sequences of step events with varying lengths (1-100)
   * 2. Verify each stepNumber equals its index + 1
   * 3. Verify no gaps in the sequence
   * 4. Verify sequence starts at 1
   * 5. Run 100+ iterations for comprehensive coverage
   */
  it('property: step numbers increment sequentially from 1 with no gaps', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          // Generate random sequence length (1-100 steps)
          sequenceLength: fc.integer({ min: 1, max: 100 }),

          // Generate random tool call ID
          toolCallId: fc.string({ minLength: 5, maxLength: 20 }),

          // Generate random total steps (should be >= sequenceLength)
          totalSteps: fc.integer({ min: 1, max: 100 }),
        }),

        async (scenario) => {
          // Ensure totalSteps is at least as large as sequenceLength
          const totalSteps = Math.max(scenario.totalSteps, scenario.sequenceLength);

          // Generate sequence of step events
          const stepEvents: SubAgentProgressEvent[] = [];

          for (let i = 1; i <= scenario.sequenceLength; i++) {
            stepEvents.push({
              type: 'step',
              toolCallId: scenario.toolCallId,
              timestamp: new Date(Date.now() + i * 1000).toISOString(),
              stepNumber: i,
              totalSteps: totalSteps,
            });
          }

          // PROPERTY VERIFICATION: Step numbers form sequential sequence [1, 2, 3, ..., N]

          // 1. Verify sequence starts at 1
          expect(stepEvents[0].stepNumber).toBe(1);

          // 2. Verify each step number equals its index + 1 (sequential with no gaps)
          for (let i = 0; i < stepEvents.length; i++) {
            const expectedStepNumber = i + 1;
            const actualStepNumber = stepEvents[i].stepNumber;

            expect(actualStepNumber).toBe(expectedStepNumber);
          }

          // 3. Verify no duplicates (each step number appears exactly once)
          const stepNumbers = stepEvents.map(e => e.stepNumber);
          const uniqueStepNumbers = new Set(stepNumbers);
          expect(uniqueStepNumbers.size).toBe(stepEvents.length);

          // 4. Verify sequence is continuous (no gaps)
          for (let i = 1; i < stepEvents.length; i++) {
            const prevStepNumber = stepEvents[i - 1].stepNumber!;
            const currentStepNumber = stepEvents[i].stepNumber!;

            // Current step should be exactly 1 more than previous step
            expect(currentStepNumber).toBe(prevStepNumber + 1);
          }

          // 5. Verify final step number equals sequence length
          const finalStepNumber = stepEvents[stepEvents.length - 1].stepNumber;
          expect(finalStepNumber).toBe(scenario.sequenceLength);
        }
      ),
      { numRuns: 100 } // Run 100+ iterations as specified
    );
  });

  /**
   * Property Test: Step counter consistency across different event types
   *
   * This test verifies that step numbers remain sequential even when
   * interleaved with other event types (reasoning, action, screenshot).
   *
   * Test Strategy:
   * 1. Generate sequences with mixed event types
   * 2. Extract only step events
   * 3. Verify step numbers are still sequential
   */
  it('property: step numbers remain sequential when interleaved with other events', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          // Generate random sequence length (1-100 steps)
          sequenceLength: fc.integer({ min: 1, max: 100 }),

          // Generate random tool call ID
          toolCallId: fc.string({ minLength: 5, maxLength: 20 }),

          // Whether to include reasoning events
          includeReasoning: fc.boolean(),

          // Whether to include action events
          includeAction: fc.boolean(),

          // Whether to include screenshot events
          includeScreenshot: fc.boolean(),
        }),

        async (scenario) => {
          // Generate sequence of mixed events
          const allEvents: SubAgentProgressEvent[] = [];

          for (let i = 1; i <= scenario.sequenceLength; i++) {
            // Always add step event
            allEvents.push({
              type: 'step',
              toolCallId: scenario.toolCallId,
              timestamp: new Date(Date.now() + allEvents.length * 100).toISOString(),
              stepNumber: i,
              totalSteps: scenario.sequenceLength,
            });

            // Optionally add reasoning event
            if (scenario.includeReasoning) {
              allEvents.push({
                type: 'reasoning',
                toolCallId: scenario.toolCallId,
                timestamp: new Date(Date.now() + allEvents.length * 100).toISOString(),
                stepNumber: i,
                content: `Reasoning for step ${i}`,
              });
            }

            // Optionally add action event
            if (scenario.includeAction) {
              allEvents.push({
                type: 'action',
                toolCallId: scenario.toolCallId,
                timestamp: new Date(Date.now() + allEvents.length * 100).toISOString(),
                stepNumber: i,
                action: {
                  type: 'left_click',
                  params: { coordinate: [100, 200] },
                  description: `Action for step ${i}`,
                },
              });
            }

            // Optionally add screenshot event
            if (scenario.includeScreenshot) {
              allEvents.push({
                type: 'screenshot',
                toolCallId: scenario.toolCallId,
                timestamp: new Date(Date.now() + allEvents.length * 100).toISOString(),
                stepNumber: i,
                screenshot: {
                  base64: 'fake-base64-data',
                  width: 1920,
                  height: 1080,
                },
              });
            }
          }

          // Extract only step events
          const stepEvents = allEvents.filter(e => e.type === 'step');

          // PROPERTY VERIFICATION: Step events still form sequential sequence

          // 1. Verify we have the expected number of step events
          expect(stepEvents.length).toBe(scenario.sequenceLength);

          // 2. Verify sequence starts at 1
          expect(stepEvents[0].stepNumber).toBe(1);

          // 3. Verify each step number equals its index + 1
          for (let i = 0; i < stepEvents.length; i++) {
            expect(stepEvents[i].stepNumber).toBe(i + 1);
          }

          // 4. Verify no gaps in sequence
          for (let i = 1; i < stepEvents.length; i++) {
            const prevStepNumber = stepEvents[i - 1].stepNumber!;
            const currentStepNumber = stepEvents[i].stepNumber!;
            expect(currentStepNumber).toBe(prevStepNumber + 1);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property Test: Step counter edge cases
   *
   * This test verifies step counter behavior for edge cases:
   * - Single step execution (N=1)
   * - Maximum length execution (N=100)
   * - Different totalSteps values
   */
  it('property: step counter handles edge cases correctly', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          // Test edge case sequence lengths
          sequenceLength: fc.constantFrom(1, 2, 50, 99, 100),

          // Generate random tool call ID
          toolCallId: fc.string({ minLength: 5, maxLength: 20 }),
        }),

        async (scenario) => {
          // Generate sequence of step events
          const stepEvents: SubAgentProgressEvent[] = [];

          for (let i = 1; i <= scenario.sequenceLength; i++) {
            stepEvents.push({
              type: 'step',
              toolCallId: scenario.toolCallId,
              timestamp: new Date(Date.now() + i * 1000).toISOString(),
              stepNumber: i,
              totalSteps: scenario.sequenceLength,
            });
          }

          // PROPERTY VERIFICATION: Even edge cases maintain sequential property

          // 1. Single step case (N=1)
          if (scenario.sequenceLength === 1) {
            expect(stepEvents[0].stepNumber).toBe(1);
            expect(stepEvents[0].totalSteps).toBe(1);
          }

          // 2. Maximum length case (N=100)
          if (scenario.sequenceLength === 100) {
            expect(stepEvents[0].stepNumber).toBe(1);
            expect(stepEvents[99].stepNumber).toBe(100);
            expect(stepEvents[99].totalSteps).toBe(100);
          }

          // 3. General verification for all edge cases
          for (let i = 0; i < stepEvents.length; i++) {
            expect(stepEvents[i].stepNumber).toBe(i + 1);
          }

          // 4. Verify no gaps
          for (let i = 1; i < stepEvents.length; i++) {
            expect(stepEvents[i].stepNumber).toBe(stepEvents[i - 1].stepNumber! + 1);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * Property Test: Step counter with multiple concurrent sub-agents
   *
   * This test verifies that step counters for different sub-agents
   * (different toolCallIds) maintain independent sequential sequences.
   */
  it('property: step counters are independent across concurrent sub-agents', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.record({
          // Number of concurrent sub-agents (2-5)
          numSubAgents: fc.integer({ min: 2, max: 5 }),

          // Sequence lengths for each sub-agent (1-50 steps each)
          sequenceLengths: fc.array(fc.integer({ min: 1, max: 50 }), { minLength: 2, maxLength: 5 }),
        }),

        async (scenario) => {
          // Ensure we have the right number of sequence lengths
          const sequenceLengths = scenario.sequenceLengths.slice(0, scenario.numSubAgents);
          while (sequenceLengths.length < scenario.numSubAgents) {
            sequenceLengths.push(10); // Default length
          }

          // Generate events for multiple concurrent sub-agents
          const eventsByToolCallId = new Map<string, SubAgentProgressEvent[]>();

          for (let agentIndex = 0; agentIndex < scenario.numSubAgents; agentIndex++) {
            const toolCallId = `call_agent_${agentIndex}`;
            const sequenceLength = sequenceLengths[agentIndex];
            const events: SubAgentProgressEvent[] = [];

            for (let i = 1; i <= sequenceLength; i++) {
              events.push({
                type: 'step',
                toolCallId: toolCallId,
                timestamp: new Date(Date.now() + agentIndex * 10000 + i * 1000).toISOString(),
                stepNumber: i,
                totalSteps: sequenceLength,
              });
            }

            eventsByToolCallId.set(toolCallId, events);
          }

          // PROPERTY VERIFICATION: Each sub-agent maintains independent sequential counter

          for (const [toolCallId, events] of eventsByToolCallId.entries()) {
            // 1. Verify sequence starts at 1
            expect(events[0].stepNumber).toBe(1);

            // 2. Verify sequential increment
            for (let i = 0; i < events.length; i++) {
              expect(events[i].stepNumber).toBe(i + 1);
            }

            // 3. Verify no gaps
            for (let i = 1; i < events.length; i++) {
              expect(events[i].stepNumber).toBe(events[i - 1].stepNumber! + 1);
            }

            // 4. Verify all events have the same toolCallId
            for (const event of events) {
              expect(event.toolCallId).toBe(toolCallId);
            }
          }

          // 5. Verify different sub-agents have different toolCallIds
          const toolCallIds = Array.from(eventsByToolCallId.keys());
          const uniqueToolCallIds = new Set(toolCallIds);
          expect(uniqueToolCallIds.size).toBe(scenario.numSubAgents);
        }
      ),
      { numRuns: 100 }
    );
  });
});
